'''
Created on Sep 9, 2013

@author: diana.tzinov
'''
from Create.TestCreateObjectsAsSetupForLocalRun import TestCreateObjectsAsSetupForLocalRun
from Mapping.TestContractMapLHN import TestContractMapLHN
from Mapping.TestContractMapWidget import TestContractMapWidget
from Mapping.TestControlMapLHN import TestControlMapLHN
from Mapping.TestControlMapWidget import TestControlMapWidget
from Mapping.TestDataAssetMapLHN import TestDataAssetMapLHN
from Mapping.TestDataAssetMapWidget import TestDataAssetMapWidget
from Mapping.TestFacilityMapLHN import TestFacilityMapLHN
from Mapping.TestFacilityMapWidget import TestFacilityMapWidget
from Mapping.TestMarketMapLHN import TestMarketMapLHN
from Mapping.TestMarketMapWidget import TestMarketMapWidget
from Mapping.TestOrgGroupMapLHN import TestOrgGroupMapLHN
from Mapping.TestOrgGroupMapWidget import TestOrgGroupMapWidget
from Mapping.TestPolicyMapLHN import TestPolicyMapLHN
from Mapping.TestPolicyMapWidget import TestPolicyMapWidget
from Mapping.TestProcessMapLHN import TestProcessMapLHN
from Mapping.TestProcessMapWidget import TestProcessMapWidget
from Mapping.TestProductMapLHN import TestProductMapLHN
from Mapping.TestProductMapWidget import TestProductMapWidget
from Mapping.TestProgramMapLHN import TestProgramMapLHN
from Mapping.TestProgramMapWidget import TestProgramMapWidget
from Mapping.TestProjectMapLHN import TestProjectMapLHN
from Mapping.TestProjectMapWidget import TestProjectMapWidget
from Mapping.TestRegulationMapLHN import TestRegulationMapLHN
from Mapping.TestRegulationMapWidget import TestRegulationMapWidget
from Mapping.TestSystemMapWidget import TestSystemMapWidget
from Mapping.TestSystemsMapLHN import TestSystemsMapLHN