'''
Updated on Oct 06, 2014

@author: ukyo.duong
'''
from Create.TestCreateObjectsAsSetup import TestCreateObjectsAsSetup
from Mapping.TestContractMapLHN import TestContractMapLHN
from Mapping.TestControlMapLHN import TestControlMapLHN
from Mapping.TestDataAssetMapLHN import TestDataAssetMapLHN
from Mapping.TestFacilityMapLHN import TestFacilityMapLHN
from Mapping.TestMarketMapLHN import TestMarketMapLHN
from Mapping.TestOrgGroupMapLHN import TestOrgGroupMapLHN
from Mapping.TestPolicyMapLHN import TestPolicyMapLHN
from Mapping.TestProcessMapLHN import TestProcessMapLHN
from Mapping.TestProductMapLHN import TestProductMapLHN
from Mapping.TestProgramMapLHN import TestProgramMapLHN
from Mapping.TestProjectMapLHN import TestProjectMapLHN
from Mapping.TestRegulationMapLHN import TestRegulationMapLHN
from Mapping.TestSystemsMapLHN import TestSystemsMapLHN
from Mapping.TestControlMapWidget import TestControlMapWidget
from Mapping.TestDataAssetMapWidget import TestDataAssetMapWidget
from Mapping.TestFacilityMapWidget import TestFacilityMapWidget
from Mapping.TestMarketMapWidget import TestMarketMapWidget
from Mapping.TestOrgGroupMapWidget import TestOrgGroupMapWidget
from Mapping.TestProcessMapWidget import TestProcessMapWidget
from Mapping.TestProductMapWidget import TestProductMapWidget
from Mapping.TestProjectMapWidget import TestProjectMapWidget
from Mapping.TestSystemMapWidget import TestSystemMapWidget
from Mapping.TestContractMapWidget import TestContractMapWidget
from Mapping.TestProgramMapWidget import TestProgramMapWidget
from Mapping.TestRegulationMapWidget import TestRegulationMapWidget
from Mapping.TestPolicyMapWidget import TestPolicyMapWidget