'''
Created on Oct 28, 2014

@author: ukyo.duong


'''

import unittest

from RapidDataEntry.TestHideShowNewModalAudit import TestHideShowNewModalAudit
from RapidDataEntry.TestSaveAndAddAnotherWorkflow import TestSaveAndAddAnotherWorkflow
from RapidDataEntry.TestHideShowNewModalProgram import TestHideShowNewModalProgram
from RapidDataEntry.TestHideShowNewModalPolicy import TestHideShowNewModalPolicy
from RapidDataEntry.TestHideShowNewModalRegulation import TestHideShowNewModalRegulation
from RapidDataEntry.TestHideShowNewModalControl import TestHideShowNewModalControl
from RapidDataEntry.TestHideShowNewModalObjective import TestHideShowNewModalObjective
from RapidDataEntry.TestHideShowNewModalStandard import TestHideShowNewModalStandard
from RapidDataEntry.TestHideShowNewModalContract import TestHideShowNewModalContract
from RapidDataEntry.TestHideShowNewModalClause import TestHideShowNewModalClause
from RapidDataEntry.TestHideShowNewModalSection import TestHideShowNewModalSection
from RapidDataEntry.TestHideShowNewModalPeople import TestHideShowNewModalPeople
from RapidDataEntry.TestHideShowNewModalOrgGroup import TestHideShowNewModalOrgGroup
from RapidDataEntry.TestHideShowNewModalVendor import TestHideShowNewModalVendor
from RapidDataEntry.TestHideShowNewModalProcess import TestHideShowNewModalProcess
from RapidDataEntry.TestHideShowNewModalSystem import TestHideShowNewModalSystem
from RapidDataEntry.TestHideShowNewModalDataAsset import TestHideShowNewModalDataAsset
from RapidDataEntry.TestHideShowNewModalProduct import TestHideShowNewModalProduct
from RapidDataEntry.TestHideShowNewModalProject import TestHideShowNewModalProject
from RapidDataEntry.TestHideShowNewModalFacility import TestHideShowNewModalFacility
from RapidDataEntry.TestHideShowNewModalMarket import TestHideShowNewModalMarket