'''
Created on Jan 16, 2015

@author: uduong
'''

import unittest

from RapidDataEntry.TestHideShowNewModalPolicy import TestHideShowNewModalPolicy
from RapidDataEntry.TestHideShowNewModalProgram import TestHideShowNewModalProgram
from RapidDataEntry.TestHideShowNewModalRegulation import TestHideShowNewModalRegulation
from RapidDataEntry.TestSaveAndAddAnotherAudit import TestSaveAndAddAnotherAudit
from RapidDataEntry.TestSaveAndAddAnotherContract import TestSaveAndAddAnotherContract
from RapidDataEntry.TestSaveAndAddAnotherControl import TestSaveAndAddAnotherControl
from RapidDataEntry.TestSaveAndAddAnotherProgram import TestSaveAndAddAnotherProgram
from RapidDataEntry.TestSaveAndAddAnotherRegulation import TestSaveAndAddAnotherRegulation
from RapidDataEntry.TestSaveAndAddAnotherWorkflow import TestSaveAndAddAnotherWorkflow
from RapidDataEntry.TestHideShowNewModalObjective import TestHideShowNewModalObjective
from RapidDataEntry.TestHideShowNewModalStandard import TestHideShowNewModalStandard
from RapidDataEntry.TestHideShowNewModalClause import TestHideShowNewModalClause
from RapidDataEntry.TestHideShowNewModalSection import TestHideShowNewModalSection
from RapidDataEntry.TestHideShowNewModalPeople import TestHideShowNewModalPeople
from RapidDataEntry.TestHideShowNewModalOrgGroup import TestHideShowNewModalOrgGroup
from RapidDataEntry.TestHideShowNewModalVendor import TestHideShowNewModalVendor
from RapidDataEntry.TestHideShowNewModalProcess import TestHideShowNewModalProcess
from RapidDataEntry.TestHideShowNewModalSystem import TestHideShowNewModalSystem
from RapidDataEntry.TestHideShowNewModalDataAsset import TestHideShowNewModalDataAsset
from RapidDataEntry.TestHideShowNewModalProduct import TestHideShowNewModalProduct
from RapidDataEntry.TestHideShowNewModalProject import TestHideShowNewModalProject
from RapidDataEntry.TestHideShowNewModalFacility import TestHideShowNewModalFacility
from RapidDataEntry.TestHideShowNewModalMarket import TestHideShowNewModalMarket