'''
Created on Jan 16, 2015

@author: uduong
'''

import unittest
from RapidDataEntry.TestSaveAndAddAnotherAudit import TestSaveAndAddAnotherAudit
from RapidDataEntry.TestSaveAndAddAnotherContract import TestSaveAndAddAnotherContract
from RapidDataEntry.TestSaveAndAddAnotherControl import TestSaveAndAddAnotherControl
from RapidDataEntry.TestSaveAndAddAnotherProgram import TestSaveAndAddAnotherProgram
from RapidDataEntry.TestSaveAndAddAnotherRegulation import TestSaveAndAddAnotherRegulation
from RapidDataEntry.TestSaveAndAddAnotherWorkflow import TestSaveAndAddAnotherWorkflow
from RapidDataEntry.TestSaveAndAddAnotherClause import TestSaveAndAddAnotherClause
from RapidDataEntry.TestSaveAndAddAnotherDataAsset import TestSaveAndAddAnotherDataAsset
from RapidDataEntry.TestSaveAndAddAnotherFacility import TestSaveAndAddAnotherFacility
from RapidDataEntry.TestSaveAndAddAnotherMarket import TestSaveAndAddAnotherMarket
from RapidDataEntry.TestSaveAndAddAnotherObjective import TestSaveAndAddAnotherObjective
from RapidDataEntry.TestSaveAndAddAnotherOrgGroup import TestSaveAndAddAnotherOrgGroup
from RapidDataEntry.TestSaveAndAddAnotherPeople import TestSaveAndAddAnotherPerson
from RapidDataEntry.TestSaveAndAddAnotherPolicy import TestSaveAndAddAnotherPolicy
from RapidDataEntry.TestSaveAndAddAnotherProcess import TestSaveAndAddAnotherProcess
from RapidDataEntry.TestSaveAndAddAnotherProduct import TestSaveAndAddAnotherProduct
from RapidDataEntry.TestSaveAndAddAnotherProject import TestSaveAndAddAnotherProject
from RapidDataEntry.TestSaveAndAddAnotherSection import TestSaveAndAddAnotherSection
from RapidDataEntry.TestSaveAndAddAnotherStandard import TestSaveAndAddAnotherStandard
from RapidDataEntry.TestSaveAndAddAnotherSystem import TestSaveAndAddAnotherSystem
from RapidDataEntry.TestSaveAndAddAnotherVendor import TestSaveAndAddAnotherVendor