SELECTOR = ".inner-nav-item"

CLAUSES = "Clauses"
CONTRACTS = "Contracts"
DATA_ASSETS = "Data Assets"
FACILITIES = "Facilities"
MARKETS = "Markets"
ORG_GROUPS = "Org Groups"
POLICIES = "Policies"
PROCESSES = "Processes"
PRODUCTS = "Products"
PROJECTS = "Projects"
STANDARDS = "Standards"
SYSTEMS = "Systems"
VENDORS = "Vendors"
THREAD_ACTORS = "Thread Actors"
RISKS = "Risks"
TASKS = "Tasks"
